################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 1.12
##  \   \         Application : Virtex-6 FPGA GTX Transceiver Wizard
##  /   /         Filename : vcs_session.tcl
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\ 
##
##
##
## Script VCS_SESSION.TCL
## Generated by Xilinx Virtex-6 FPGA GTH Transceiver Wizard
##
## 
## (c) Copyright 2009-2011 Xilinx, Inc. All rights reserved.
## 
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
## 
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.

  gui_open_window Wave
  gui_sg_create xaui_wrapper_Group
  gui_list_add_group -id Wave.1 {xaui_wrapper_Group}

  gui_sg_addsignal -group xaui_wrapper_Group {{FRAME_CHECK_MODULE}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx0_frame_check.begin_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx0_frame_check.track_data_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx0_frame_check.data_error_detected_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx0_frame_check.start_of_packet_detected_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx0_frame_check.RX_DATA}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx0_frame_check.ERROR_COUNT}
  gui_sg_addsignal -group xaui_wrapper_Group {{FRAME_CHECK_MODULE}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx1_frame_check.begin_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx1_frame_check.track_data_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx1_frame_check.data_error_detected_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx1_frame_check.start_of_packet_detected_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx1_frame_check.RX_DATA}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx1_frame_check.ERROR_COUNT}
  gui_sg_addsignal -group xaui_wrapper_Group {{FRAME_CHECK_MODULE}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx2_frame_check.begin_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx2_frame_check.track_data_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx2_frame_check.data_error_detected_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx2_frame_check.start_of_packet_detected_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx2_frame_check.RX_DATA}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx2_frame_check.ERROR_COUNT}
  gui_sg_addsignal -group xaui_wrapper_Group {{FRAME_CHECK_MODULE}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx3_frame_check.begin_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx3_frame_check.track_data_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx3_frame_check.data_error_detected_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx3_frame_check.start_of_packet_detected_r}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx3_frame_check.RX_DATA}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.gtx3_frame_check.ERROR_COUNT}
  gui_sg_addsignal -group xaui_wrapper_Group {{GTX0_XAUI_WRAPPER}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {{Loopback and Powerdown Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.LOOPBACK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXPOWERDOWN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXPOWERDOWN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - 8b10b Decoder}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXCHARISCOMMA_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXCHARISK_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXDISPERR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXNOTINTABLE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Channel Bonding Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXCHANBONDSEQ_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXENCHANSYNC_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Clock Correction Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXCLKCORCNT_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Comma Detection and Alignment}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXBYTEISALIGNED_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXBYTEREALIGN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXCOMMADET_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXENMCOMMAALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXENPCOMMAALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - PRBS Detection}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.PRBSCNTRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXENPRBSTST_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXPRBSERR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Data Path interface}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXDATA_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXUSRCLK2_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXCDRRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXELECIDLE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXEQMIX_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXP_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Elastic Buffer and Phase Alignment Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXBUFRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXBUFSTATUS_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXCHANISALIGNED_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXCHANREALIGN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Loss-of-sync State Machine}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXLOSSOFSYNC_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX PLL Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.GTXRXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.MGTREFCLKRX_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.PLLRXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXPLLLKDET_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.RXRESETDONE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Shared Ports - Dynamic Reconfiguration Port (DRP)}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.DADDR_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.DCLK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.DEN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.DI_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.DRDY_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.DRPDO_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.DWE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - 8b10b Encoder Control Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXCHARISK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Data Path interface}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXDATA_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXOUTCLK_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXUSRCLK2_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Driver and OOB signaling}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXDIFFCTRL_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXP_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXPOSTEMPHASIS_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Driver and OOB signalling}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXPREEMPHASIS_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Elastic Buffer and Phase Alignment Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXDLYALIGNDISABLE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXDLYALIGNMONENB_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXDLYALIGNMONITOR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXDLYALIGNRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXENPMAPHASEALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXPMASETPHASE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX PLL Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.GTXTXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXRESETDONE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX PRBS Generator}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXENPRBSTST_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXPRBSFORCEERR_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Ports for PCI Express}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx0_xaui_wrapper_i.TXELECIDLE_IN}

  gui_sg_addsignal -group xaui_wrapper_Group {{GTX1_XAUI_WRAPPER}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {{Loopback and Powerdown Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.LOOPBACK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXPOWERDOWN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXPOWERDOWN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - 8b10b Decoder}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXCHARISCOMMA_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXCHARISK_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXDISPERR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXNOTINTABLE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Channel Bonding Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXCHANBONDSEQ_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXENCHANSYNC_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Clock Correction Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXCLKCORCNT_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Comma Detection and Alignment}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXBYTEISALIGNED_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXBYTEREALIGN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXCOMMADET_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXENMCOMMAALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXENPCOMMAALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - PRBS Detection}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.PRBSCNTRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXENPRBSTST_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXPRBSERR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Data Path interface}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXDATA_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXUSRCLK2_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXCDRRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXELECIDLE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXEQMIX_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXP_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Elastic Buffer and Phase Alignment Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXBUFRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXBUFSTATUS_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXCHANISALIGNED_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXCHANREALIGN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Loss-of-sync State Machine}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXLOSSOFSYNC_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX PLL Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.GTXRXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.MGTREFCLKRX_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.PLLRXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXPLLLKDET_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.RXRESETDONE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Shared Ports - Dynamic Reconfiguration Port (DRP)}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.DADDR_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.DCLK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.DEN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.DI_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.DRDY_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.DRPDO_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.DWE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - 8b10b Encoder Control Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXCHARISK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Data Path interface}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXDATA_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXOUTCLK_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXUSRCLK2_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Driver and OOB signaling}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXDIFFCTRL_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXP_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXPOSTEMPHASIS_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Driver and OOB signalling}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXPREEMPHASIS_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Elastic Buffer and Phase Alignment Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXDLYALIGNDISABLE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXDLYALIGNMONENB_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXDLYALIGNMONITOR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXDLYALIGNRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXENPMAPHASEALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXPMASETPHASE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX PLL Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.GTXTXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXRESETDONE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX PRBS Generator}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXENPRBSTST_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXPRBSFORCEERR_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Ports for PCI Express}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx1_xaui_wrapper_i.TXELECIDLE_IN}

  gui_sg_addsignal -group xaui_wrapper_Group {{GTX2_XAUI_WRAPPER}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {{Loopback and Powerdown Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.LOOPBACK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXPOWERDOWN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXPOWERDOWN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - 8b10b Decoder}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXCHARISCOMMA_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXCHARISK_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXDISPERR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXNOTINTABLE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Channel Bonding Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXCHANBONDSEQ_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXENCHANSYNC_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Clock Correction Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXCLKCORCNT_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Comma Detection and Alignment}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXBYTEISALIGNED_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXBYTEREALIGN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXCOMMADET_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXENMCOMMAALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXENPCOMMAALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - PRBS Detection}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.PRBSCNTRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXENPRBSTST_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXPRBSERR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Data Path interface}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXDATA_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXUSRCLK2_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXCDRRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXELECIDLE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXEQMIX_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXP_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Elastic Buffer and Phase Alignment Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXBUFRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXBUFSTATUS_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXCHANISALIGNED_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXCHANREALIGN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Loss-of-sync State Machine}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXLOSSOFSYNC_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX PLL Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.GTXRXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.MGTREFCLKRX_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.PLLRXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXPLLLKDET_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.RXRESETDONE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Shared Ports - Dynamic Reconfiguration Port (DRP)}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.DADDR_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.DCLK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.DEN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.DI_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.DRDY_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.DRPDO_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.DWE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - 8b10b Encoder Control Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXCHARISK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Data Path interface}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXDATA_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXOUTCLK_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXUSRCLK2_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Driver and OOB signaling}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXDIFFCTRL_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXP_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXPOSTEMPHASIS_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Driver and OOB signalling}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXPREEMPHASIS_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Elastic Buffer and Phase Alignment Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXDLYALIGNDISABLE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXDLYALIGNMONENB_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXDLYALIGNMONITOR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXDLYALIGNRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXENPMAPHASEALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXPMASETPHASE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX PLL Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.GTXTXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXRESETDONE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX PRBS Generator}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXENPRBSTST_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXPRBSFORCEERR_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Ports for PCI Express}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx2_xaui_wrapper_i.TXELECIDLE_IN}

  gui_sg_addsignal -group xaui_wrapper_Group {{GTX3_XAUI_WRAPPER}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {{Loopback and Powerdown Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.LOOPBACK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXPOWERDOWN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXPOWERDOWN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - 8b10b Decoder}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXCHARISCOMMA_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXCHARISK_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXDISPERR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXNOTINTABLE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Channel Bonding Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXCHANBONDSEQ_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXENCHANSYNC_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Clock Correction Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXCLKCORCNT_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - Comma Detection and Alignment}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXBYTEISALIGNED_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXBYTEREALIGN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXCOMMADET_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXENMCOMMAALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXENPCOMMAALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - PRBS Detection}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.PRBSCNTRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXENPRBSTST_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXPRBSERR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Data Path interface}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXDATA_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXUSRCLK2_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXCDRRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXELECIDLE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXEQMIX_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXP_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Elastic Buffer and Phase Alignment Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXBUFRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXBUFSTATUS_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXCHANISALIGNED_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXCHANREALIGN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX Loss-of-sync State Machine}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXLOSSOFSYNC_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Receive Ports - RX PLL Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.GTXRXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.MGTREFCLKRX_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.PLLRXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXPLLLKDET_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.RXRESETDONE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Shared Ports - Dynamic Reconfiguration Port (DRP)}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.DADDR_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.DCLK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.DEN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.DI_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.DRDY_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.DRPDO_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.DWE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - 8b10b Encoder Control Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXCHARISK_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Data Path interface}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXDATA_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXOUTCLK_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXUSRCLK2_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Driver and OOB signaling}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXDIFFCTRL_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXN_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXP_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXPOSTEMPHASIS_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Driver and OOB signalling}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXPREEMPHASIS_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Elastic Buffer and Phase Alignment Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXDLYALIGNDISABLE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXDLYALIGNMONENB_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXDLYALIGNMONITOR_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXDLYALIGNRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXENPMAPHASEALIGN_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXPMASETPHASE_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX PLL Ports}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.GTXTXRESET_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXRESETDONE_OUT}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX PRBS Generator}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXENPRBSTST_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXPRBSFORCEERR_IN}
  gui_sg_addsignal -group xaui_wrapper_Group {{Transmit Ports - TX Ports for PCI Express}} -divider
  gui_sg_addsignal -group xaui_wrapper_Group {DEMO_TB.xaui_wrapper_top_i.xaui_wrapper_i.gtx3_xaui_wrapper_i.TXELECIDLE_IN}


  gui_zoom -window Wave.1 -full

